---
title: "AirPassenger_TimeSeriesForecast"
author: "Himanshi"
date: "2025-08-08"
output:
  html_document: default
  pdf_document: default
---

## Project Overview
This project analyzes the `AirPassengers` dataset in R, which contains monthly totals of international airline passengers from 1949 to 1960.  
The goal is to explore patterns, detect seasonality, and forecast future passenger numbers.

---

## Loading the Data
```{r}
# Load the built-in dataset
data(AirPassengers)
ts_data <- AirPassengers
```
# Basic summary
```{r}
summary(ts_data)
```
```{r}

plot(ts_data,
     main="Monthly Airline Passenger Numbers (1949–1960)",
     ylab="Passengers (1000s)",
     xlab="Year",
     col="blue",
     lwd=2)
```
# Decompose of the time series
```{r}
decomposed <- decompose(ts_data)
plot(decomposed)
```
# Forecast
```{r}

library(forecast)
model <- auto.arima(ts_data)
forecasted <- forecast(model, h=24)
plot(forecasted)
```
# Calculate a simple moving average for smoothing
```{r}
ma <- filter(ts_data, rep(1/12, 12), sides=2)
plot(ts_data, col="blue", main="AirPassengers with Moving Average")
lines(ma, col="red", lwd=2)
legend("topleft", legend=c("Original", "12-Month MA"),
       col=c("blue", "red"), lty=1, bty="n")
```
